version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - gen
    desc: "Generate from Protobuf"
    cmds:
      - PATH="${PATH}:${HOME}/go/bin" protoc --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative proto/auth.proto
